{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1/ClusterSecretStore" -}}
apiVersion: external-secrets.io/v1
{{- else -}}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: ClusterSecretStore
metadata:
  name: "secret-store-parameter-store"
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.region }}
      role: {{ .Values.role }} # role is created via helm-release; see `service_account_set_key_path`
